name: V1

on: 
  push:
    branches:
      - main
jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: printing
        run: |
          echo "hello world"
          echo "v1 successful"