name: V1

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: printing
        run: |
          echo "hello world"
          echo "v1 successful"
        shell: bash
